import {Inter} from 'next/font/google'
import '../globals.css'
import {GlobalContextProvider} from "../Context/contextApi";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Nikhil Ganireddy', description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }) {
    return (<html lang="en">
    <body className={`bg-black text-white h-screen ${inter.className}`}>
    <GlobalContextProvider>
        {children}
    </GlobalContextProvider>
    </body>
    </html>)
}
